import type { Metadata } from "next";
import localFont from 'next/font/local'
import { Geist, Geist_Mono,  } from "next/font/google";
import ThemeProvider from "@/components/theme-provider/page";
import './globals.css'
import CheckContext from "./context/page";

import { SessionProvider } from "next-auth/react";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const oldStandard = localFont ({
   src: './fonts/OldStandardTT-Regular.ttf',
   variable: "--font-old-standard"
})

const baloo = localFont({
  src: './fonts/Baloo2-Regular.ttf',
  variable: '--font-baloo2',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default  function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  

  return (
     <html lang="en" className={`${geistSans.variable} ${geistMono.variable} ${oldStandard.variable} ${baloo.variable}`}>
    <body className="antialiased">
      <SessionProvider >
       <CheckContext>
      {children}
      <ThemeProvider />
        </CheckContext>
        </SessionProvider>
    </body>
  </html>
  );
}
