
import type { Metadata } from "next"
import localFont from "next/font/local"
import Navbar from "../layouts/navbar/page"
import ThemeProvider from "@/components/theme-provider/page"
import CheckContext from "@/app/context/page"

const oldStandard = localFont({
  src: "../../fonts/OldStandardTT-Regular.ttf",
  variable: "--font-old-standard",
})

export const metadata: Metadata = {
  title: "Product Page",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
     
      <div className={`${oldStandard.variable}`}>
         <CheckContext>

       
        <Navbar />
        {children}
        <ThemeProvider />
          </CheckContext>
      </div>
    
  )
}